SELECT YEAR(b.SALES_DATE) as YEAR, MONTH(b.SALES_DATE) as MONTH, a.GENDER,
# 동일한 날짜, 회원 ID, 상품 ID 조합에 대해서는 하나의 판매 데이터만 존재
COUNT(DISTINCT a.USER_ID) as USERS
FROM USER_INFO a
JOIN ONLINE_SALE b
ON a.USER_ID = b.USER_ID
# 성별 정보가 없는 경우 결과에서 제외
WHERE GENDER IS NOT NULL
GROUP BY YEAR(b.SALES_DATE), MONTH(b.SALES_DATE), a.GENDER
ORDER BY 1,2,3;