SELECT MONTH(START_DATE) as MONTH, CAR_ID, COUNT(*) as RECORDS
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE CAR_ID in (
    # 2022년 8월부터 2022년 10월까지 총 대여 횟수가 5회 이상인 자동차들에 대해서
    SELECT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE START_DATE like '2022-08%'
        or START_DATE like '2022-09%'
        or START_DATE like '2022-10%'
    GROUP BY CAR_ID
    HAVING COUNT(*) >= 5
) AND (
    START_DATE like '2022-08%'
    or START_DATE like '2022-09%'
    or START_DATE like '2022-10%'
)
GROUP BY MONTH, CAR_ID
ORDER BY 1, 2 DESC;