SELECT a.MEMBER_NAME, b.REVIEW_TEXT,
DATE_FORMAT(b.REVIEW_DATE, '%Y-%m-%d') AS REVIEW_DATE
    FROM MEMBER_PROFILE a
    JOIN REST_REVIEW b
    ON a.MEMBER_ID = b.MEMBER_ID
    # 테이블에서 리뷰를 가장 많이 작성한 회원
    WHERE b.MEMBER_ID = (
        SELECT MEMBER_ID
        FROM REST_REVIEW
        GROUP BY MEMBER_ID
        ORDER BY COUNT(REVIEW_TEXT) DESC 
        LIMIT 1)
    ORDER BY b.REVIEW_DATE, b.REVIEW_TEXT;