SELECT b.AUTHOR_ID, a.AUTHOR_NAME, b.CATEGORY, SUM(bs.SALES*b.PRICE) as TOTAL_SALES
FROM BOOK b
JOIN AUTHOR a ON a.AUTHOR_ID = b.AUTHOR_ID
JOIN BOOK_SALES bs ON b.BOOK_ID = bs.BOOK_ID
WHERE bs.SALES_DATE LIKE '2022-01%'
GROUP BY a.AUTHOR_NAME, B.CATEGORY 
ORDER BY 1, 3 DESC;