SELECT a.PRODUCT_ID, a.PRODUCT_NAME, SUM(b.amount*a.PRICE) as TOTAL_SALES
FROM FOOD_PRODUCT a
JOIN FOOD_ORDER b
ON a.PRODUCT_ID = b.PRODUCT_ID
where b.PRODUCE_DATE like '2022-05%'
GROUP BY a.PRODUCT_ID
ORDER BY 3 DESC, 1;