SELECT a.REST_ID, a.REST_NAME, a.FOOD_TYPE, a.FAVORITES, a.ADDRESS,
ROUND(AVG(b.REVIEW_SCORE), 2) AS SCORE
FROM REST_INFO a
JOIN REST_REVIEW b ON a.REST_ID = b.REST_ID
# 식당별로 평균 리뷰 점수를 내야하니까
GROUP BY a.REST_ID
# 서울에 있는 식당들
HAVING a.ADDRESS LIKE '서울%' 
ORDER BY SCORE DESC, FAVORITES DESC;